ishuqian/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # ishuqian:
    url(r'^$', 'ishuqian.views.default', name='default'),
    url(r'^about/$', 'ishuqian.views.feedback', name='about'),
    url(r'^callback/(?P<social>\w+)/$','ishuqian.views.callback', name='callback'),
    url(r'^signin/$', 'ishuqian.views.signin', name='signin'),
    url(r'^logout/$','ishuqian.views.logout', name='logout'),
    url(r'^home/$', 'ishuqian.views.home', name='home'),
    url(r'^home/public/$', 'ishuqian.views.home_public', name='home_public'),
    url(r'^home/private/$', 'ishuqian.views.home_private', name='home_private'),
    url(r'^home/list/(?P<id>\d+)/$', 'ishuqian.views.home', name='home_list'),

    # bookmark
    url(r'^addurl/$', 'bookmark.views.addurl', name='addurl'),
    url(r'^new/$', 'bookmark.views.new', name='new_bookmark'),
    url(r'^edit/(?P<id>\d+)/$', 'bookmark.views.edit', name='bookmark_edit'),
    url(r'^delete/(?P<id>\d+)/$', 'bookmark.views.delete', name='bookmark_delete'),
    url(r'^list/new/$', 'bookmark.views.new_list', name='new_list'),
    url(r'^list/$', 'bookmark.views.list_index', name='list'),
    url(r'^list/(?P<id>\d+)/update/$', 'bookmark.views.list_update', name='list_update'),
    url(r'^list/(?P<id>\d+)/delete/$', 'bookmark.views.list_delete', name='list_delete'),
    url(r'^list/(?P<id>\d+)/delall/$', 'bookmark.views.list_delall', name='list_delete_all'),
    url(r'^bookmarks/change/$', 'bookmark.views.bookmarks_change', name='bookmarks_change'),
    url(r'^bookmarks/delete/$', 'bookmark.views.bookmarks_delete', name='bookmarks_delete'),
    url(r'^bookmarks/import/$', 'bookmark.views.bookmarks_import', name='bookmarks_import'),
    url(r'^bookmarks/export/$', 'bookmark.views.bookmarks_export', name='bookmarks_export'),
    # url(r'^item/(?P<id>\d+)/$', 'bookmark.views.item', name='item'),
    url(r'^item/(?P<id>\d+)/reply/$', 'bookmark.views.item_reply', name='item_reply'),
    url(r'^bookmark/(?P<id>\d+)/reply/$', 'bookmark.views.bookmark_reply', name='bookmark_reply'),
    url(r'^bookmark/(?P<id>\d+)/go/$', 'bookmark.views.bookmark_go', name='bookmark_go'),
    url(r'^item/(?P<id>\d+)/go/$', 'bookmark.views.item_go', name='item_go'),

    # user
    url(r'^user/(?P<id>\d+)/$', 'ishuqian.views.user', name='user_index'),
    url(r'^user/feed/$', 'ishuqian.views.follow_bookmarks', name='user_follow_feed'),
    url(r'^user/(?P<id>\d+)/list/(?P<cate>\d+)/$', 'ishuqian.views.user', name='user_index_cate'),
    url(r'^user/follow/$', 'ishuqian.views.follow', name='user_follow'),
    url(r'^user/(?P<id>\d+)/following/$', 'ishuqian.views.following', name='user_following'),
    url(r'^user/(?P<id>\d+)/followers/$', 'ishuqian.views.followers', name='user_followers'),

    # favorite
    url(r'^favorite/(?P<id>\d+)/people/$', 'ishuqian.views.favorite_people', name='favorite_people'),


    # url(r'^ishuqian/', include('ishuqian.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ staticfiles_urlpatterns()

if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

bookmark/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class List(models.Model):

    user      = models.ForeignKey('ishuqian.User')
    name      = models.CharField(max_length=90)
    bookmarks = models.PositiveIntegerField(default=0)
    color     = models.CharField(max_length=10, blank=True)
    addtime   = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Item(models.Model):

    url             = models.URLField(max_length=255, blank=True)
    title           = models.CharField(max_length=255, blank=True)
    favorites       = models.PositiveIntegerField(default=0)
    point           = models.PositiveIntegerField(default=0)
    votes           = models.PositiveIntegerField(default=0)
    addtime         = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

class Bookmark(models.Model):

    user        = models.ForeignKey('ishuqian.User')
    list        = models.ForeignKey(List)
    item        = models.ForeignKey(Item, null=True, blank=True)
    url         = models.URLField(max_length=255, blank=True)
    title       = models.CharField(max_length=255)
    private     = models.PositiveSmallIntegerField(default=0)
    views_count = models.PositiveIntegerField(default=0)
    addtime     = models.DateTimeField(auto_now_add=True)
    updatetime  = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

bookmark/forms.py
# -*- coding: utf-8 -*-
from django import forms

from models import Bookmark, List
from ishuqian.models import User

class BookmarkForm(forms.ModelForm):

    class Meta():
        model = Bookmark
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(attrs={'class':'input'}),
        }

bookmark/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils import simplejson

from bs4 import BeautifulSoup
from time import mktime

from forms import BookmarkForm
from utils import get_bookmark_title, current_url
from ishuqian.models import User
from models import Bookmark, List, Item
from ishuqian.utils import login_required

def addurl(request):
    if request.session.get('id', None) is None:
        request.session['redirect_url'] = request.GET.get('url', None)
        return redirect('signin')

    url   = current_url(request.GET.get('url', None).encode('utf-8'))
    title = get_bookmark_title(url)
    user  = get_object_or_404(User, id=request.session.get('id', None))

    # 添加到Item表
    try:
        item = Item.objects.get(url=url)
        try:
            # 如果书签已存在 直接跳到编辑页面
            bookmark = Bookmark.objects.get(url=item.url, user=user)
            # 如果书签通过导入文件添加 不走item表 所以bookmark表item_id为0
            if bookmark.item_id is None:
                bookmark.item = item
                bookmark.save()
                # 更新item的书签数量
                item.favorites = item.bookmark_set.count()
                item.save()
            return redirect('bookmark_edit', id=bookmark.id)
        except Bookmark.DoesNotExist:
            pass

    except Item.DoesNotExist:
        item = Item(url=url.encode('utf-8'), title=title.encode('utf-8'))
        item.save()
        try:
            # 如果书签已存在 直接跳到编辑页面
            bookmark = Bookmark.objects.get(url=item.url, user=user)
            # 如果书签通过导入文件添加 不走item表 所以bookmark表item_id为0
            if bookmark.item_id is None:
                bookmark.item = item
                bookmark.save()
                # 更新item的书签数量
                item.favorites = item.bookmark_set.count()
                item.save()
            return redirect('bookmark_edit', id=bookmark.id)
        except Bookmark.DoesNotExist:
            pass

    form = BookmarkForm(initial={'title':title})
    lists = user.list_set.all()
    return render(request, 'bookmark/new.html', {'form': form, 'lists': lists, 'item': item})


@login_required
def new(request):
    if request.method != 'POST':
        return redirect('/')
    
    user = get_object_or_404(User, id=request.session.get('id', None))
    item = get_object_or_404(Item, id=request.POST.get('item', None))

    form = BookmarkForm(request.POST)
    if form.is_valid():
        # lists = request.POST.getlist('lists');
        list = request.POST.get('list', None)
        url  = request.POST.get('url', None)

        # 如果文本框和item的url不一致说明用户修改过url 所以跳到404页面
        if item.url != url:
            raise Http404
            # return render(request, 'debug.html', {'debug': [item.url, url]})

        l = get_object_or_404(List, id=list)

        private = request.POST.get('private', None)
        if private:
            pvalue = 1
        else:
            pvalue = 0

        d = form.save(commit=False)
        d.item = item
        d.private = pvalue
        d.user = user
        d.list = l
        d.url = item.url
        d.save()

        #更新有多少用户收藏了这个书签
        item.favorites = item.bookmark_set.exclude(private=1).count()
        item.save()

        #更新list bookmark的数量
        l.bookmarks = Bookmark.objects.filter(user=user, list=list).count()
        l.save()
        user.update_bookmarks()
        return redirect('/home/')
    
    lists = user.list_set.all()
    return render(request, 'bookmark/new.html', {'form': form, 'lists': lists, 'item': item})


@csrf_exempt
@login_required
def new_list(request):
    if request.method != 'POST':
        raise Http404

    name = request.POST.get('name', None)
    if not name:
        raise Http404

    user = get_object_or_404(User, id=request.session.get('id', None))
    try:
        list = List.objects.get(name=name, user=user)
    except List.DoesNotExist:
        list = List(user=user, name=name)
        list.save()
        json = simplejson.dumps({'error': 0, 'name': list.name, 'value': list.id})
    else:
        json = simplejson.dumps({'error': 1, 'message': u'分类已存在'})

    return HttpResponse(json)


# 编辑书签
@login_required
def edit(request, id):
    bookmark = get_object_or_404(Bookmark, id=id)

    if bookmark.user.id != request.session.get('id', None):
        raise Http404

    if bookmark.item is None:
        try:
            item = Item.objects.get(url=bookmark.url)
        except Exception, e:
            title = get_bookmark_title(bookmark.url)
            item = Item(url=bookmark.url, title=title.encode('utf-8'), favorites=1)
            item.save()
        bookmark.item = item
        bookmark.save()
        item.favorites = item.bookmark_set.count()
        item.save()

    form = BookmarkForm(initial={'title':bookmark.title})

    if request.method == 'POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            list = get_object_or_404(List, id=request.POST.get('list', None))

            if bookmark.item.url != request.POST.get('url', None) or bookmark.item.id != int(request.POST.get('item', None)):
                raise Http404

            bookmark.title = request.POST.get('title')
            private = request.POST.get('private', None)
            if private:
                pvalue = 1
            else:
                pvalue = 0
            bookmark.private = pvalue
            # 如果修改了分类要更新分类表里的数据
            if bookmark.list != list:
                old_list = bookmark.list
                bookmark.list = list
                bookmark.save()
                old_list.bookmarks = Bookmark.objects.filter(user=bookmark.user, list=old_list).count()
                old_list.save()
                list.bookmarks = Bookmark.objects.filter(user=bookmark.user, list=list).count()
                list.save()
            else:
                bookmark.save()
            
            return redirect('home')

    user = get_object_or_404(User, id=request.session.get('id', None))
    lists = user.list_set.all()
    return render(request, 'bookmark/edit.html', {'form': form, 'lists': lists, 'bookmark': bookmark})


# 删除书签
@login_required
def delete(request, id):
    bookmark = get_object_or_404(Bookmark, id=id)
    bookmark.delete()
    # 更新删除书签分类数量
    bookmark.list.bookmarks = bookmark.list.bookmark_set.count()
    bookmark.list.save()
    # 更新用户书签数量
    user = get_object_or_404(User, id=request.session.get('id', None))
    user.update_bookmarks()

    return redirect(request.META.get('HTTP_REFERER', None))


# 分类列表
@login_required
def list_index(request):
    lists = get_object_or_404(User, id=request.session.get('id', None)).list_set.exclude(name=u'默认分类')
    return render(request, 'bookmark/list.html', {'lists': lists})


# 更新分类名称
@login_required
def list_update(request, id):
    if request.method != 'POST' or not request.POST.get('name', None):
        raise Http404

    list = List.objects.get(id=id, user_id=request.session.get('id', None))
    list.name = request.POST.get('name', None)
    list.save()

    return redirect('list')


# 列表删除
@login_required
def list_delete(request, id):
    list = List.objects.get(id=id, user_id=request.session.get('id', None))
    default = List.objects.get(user_id=request.session.get('id', None), name=u'默认分类')
    list.bookmark_set.all().update(list=default)
    list.delete()
    default.bookmarks = default.bookmark_set.count()
    default.save()
    return redirect('list')


# 删除列表及书签
@login_required
def list_delall(request, id):
    list = List.objects.get(id=id, user_id=request.session.get('id', None))
    list.bookmark_set.all().delete()
    list.delete()
    user = get_object_or_404(User, id=request.session.get('id', None))
    user.update_bookmarks()
    return redirect('list')


# 更新书签到列表
@login_required
def bookmarks_change(request):
    bs = request.POST.getlist('bm_box');
    id = request.POST.get('id', None)
    l = get_object_or_404(List, id=id)
    bookmarks = Bookmark.objects.filter(id__in=bs)
    lids = [b.list_id for b in bookmarks]
    lids.append(int(id))
    lids = set(lids)
    bookmarks.update(list=l)
    for l in lids:
        lt = get_object_or_404(List, id=l)
        lt.bookmarks = lt.bookmark_set.count()
        lt.save()
    return redirect(request.META.get('HTTP_REFERER', None))


# 删除多个书签
@login_required
def bookmarks_delete(request):
    bs = request.POST.getlist('bm_box');
    bookmarks = Bookmark.objects.filter(id__in=bs)
    lids = [b.list_id for b in bookmarks]
    lids = set(lids)
    bookmarks.delete()
    for l in lids:
        lt = get_object_or_404(List, id=l)
        lt.bookmarks = lt.bookmark_set.count()
        lt.save()

    # 把user bookmarks数量写成函数
    user = get_object_or_404(User, id=request.session.get('id', None))
    user.update_bookmarks()
    return redirect(request.META.get('HTTP_REFERER', None))


# 导入书签
@login_required
def bookmarks_import(request):
    user = get_object_or_404(User, id=request.session.get('id', None))
    list = List.objects.get(name=u'默认分类', user=user)
    if request.method == 'POST':
        bf = request.FILES['file']
        text = ''
        for t in bf.chunks():
            text += t

        soup = BeautifulSoup(text)
        try:
            links = soup.dl.find_all('a')
        except Exception, e:
            return HttpResponse('请导入正确的书签文件')
            
        for l in links:
            url = l.get('href').encode('utf-8')
            try:
                title = l.string.encode('utf-8')
            except Exception:
                title = url
            # bookmark是否存在
            try:
                bookmark = Bookmark.objects.get(url=url, user_id=request.session.get('id', None))
            except Bookmark.DoesNotExist:
                Bookmark.objects.create(user=user, private=0, list=list, url=url, title=title)

        list.bookmarks = list.bookmark_set.count()
        list.save()

bookmark/templates/bookmark/edit.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class='container'>

  <form class='new-bookmark-form clearfix' action="/edit/{{ bookmark.id }}/" method="post">
    {% csrf_token %}

    <div class='span8 edit fl'>
      <div class='blank clearfix'>
        <label for="id-url">书签链接:</label>
        <input class="input" maxlength="255" disabled='disabled' type="text" value="{{ bookmark.url }}">
      </div>

      <div class='blank clearfix'>
        <label for="id-title">标题:</label>
        {{ form.title }}
        {{ form.title.errors }}
      </div>

      <div class='blank clearfix'>
        <label for="id-private">是否私有:</label>
        <input id="id-private" {% if bookmark.private %}checked='checked'{% endif %} name="private" class='private' type="checkbox" value="1">
      </div>

      <div class='blank clearfix'>
        <input name="item" type="hidden" value="{{ bookmark.item.id }}">
        <input name="url" type="hidden" value="{{ bookmark.url }}">
      </div>

      <div class='blank clearfix'>
        <input class='btn' type='submit' value='保存'>
      </div>
    </div>

    <div class='span4 fr'>
      请选择分类
      <ul class='list-list'>
        {% for list in lists %}
          <li>
            <input class="list-checkbox" {% if list.id == bookmark.list_id %}checked='checked'{% endif %} id='list-{{ list.id }}' type='radio' name='list' value='{{ list.id }}'>
            <label for='list-{{ list.id }}'>{{ list.name }}</label>
          </li>
        {% endfor %}
      </ul>
      <div class='new-list'>
        <input class='new-list-name'>
        <input type='button' class='p5 new-list-sub btn' style='font-size: 12px; line-height: 20px; padding: 5px;' value='新建分类'>
      </div>
    </div>
  </form>

</div>

<script type="text/javascript">
//新建分类
var is = true;
$('.new-list-sub').click(function(){
    var name = $('.new-list-name').val();
    if (!name) {alert('请输新分类名称')};

    if (is) {
      $.post('/list/new/', {'name': name}, function(data){
        is = false;
        if (data.error) {
          alert(data.status)
        } else {
          $('.list-list').append('<li><input class="list-checkbox" id="list-' + data.value + '" type="radio" name="list" value="' + data.value + '"><label for="list-' + data.value + '">' + data.name + '<label/></li>');
          $('.new-list-name').val('');
        };
        is = true;
      }, 'json');
    }
});

$('.new-bookmark-form').submit(function(){
  url = $('#id_url').val();
  title = $('#id_title').val();
  //l = $(".list-checkbox:checked").length;]
  l = $(".list-checkbox:checked").val()
  if (!l) {
    alert('请选择分类');
    return false;
  }
  if (!url && !title && !l)
    return false;
});
</script>
{% endblock %}

bookmark/templates/bookmark/import.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class='container clearfix'>
  <div class='span7 list-wrapper fl'>
    <h3 class='list-title clearfix'>导入书签</h3>
    <div class='span5 ptb20 center'>
      <form action='/bookmarks/import/' method='post' enctype="multipart/form-data">{% csrf_token %}
        <div><label for='file' class='f16'>请选择书签文件:&nbsp;</label><input id='file' name='file' type='file'></div>
        <div class='mt15'><input class='btn import-bookmarks-submit' style='font-size:12px;width:60px;height:30px;padding:5px;' type='submit' value='提交'></div>
      </form>
    </div>
  </div>

  <div class='ml40 span4 list-wrapper fl'>
    <h3 class='list-title clearfix'>小贴士</h3>
    <div class='p10'>书签自动导入到默认分类，回到页面您可以批量管理移动到其他分类。</div>
  </div>
</div>

<script type="text/javascript">
$('.import-bookmarks-submit').click(function(){
  if(!$('#file').val()){alert('请选择书签');return false;};
});
</script>

{% endblock %}

bookmark/templates/bookmark/item.html
<!DOCTYPE html>
<html>
<head>
  <title>爱书签 | {{item.title}}</title>
  <link rel="stylesheet" type="text/css" href="/static/css/base.css">
  <script type="text/javascript" src='/static/js/jquery.js'></script>
  <style type="text/css">
    .header {
      padding: 10px;
      background: #69975B;
      height: 30px;
      position: fixed;
      right: 0;
      left: 0;
      z-index: 1030;
      margin-bottom: 0;
    }
    .title {
      font-size: 20px;
      line-height: 30px;
    }
    .header li {
      float: left;
      font-size: 14px;
      line-height: 30px;
      padding: 0 5px;
    }
    .name {
      float: left;
      font-size: 14px;
      margin-left: 20px;
      line-height: 30px;
      overflow: hidden;
      height: 30px;
    }
    a {
      color: #fff;
    }
    .iframe-body {
      width: 100%;
      margin-top: 50px;
      float:left;
    }
    .iframe {
      width: 100%;
    }
  </style>
</head>
<body>
  <div class='header mb20'>
    <div class='container nav clearfix'>
      <h1 class='title fl'><a href="{% url 'default' %}">ISHUQIAN</a></h1>
      <div class='name span9'><a href="{{ item.url }}">{{ item.title }}</a></div>

      <ul class='fr'>
        <li class='br1'><a class='add-bookmark' href="#">收藏</a></li>
        <li class='br1'><a class='add-bookmark' href="#">喜欢</a></li>
        <li class='br1'><a href="#">评论</a></li>
      </ul>
    </div>
  </div>


  <div class='iframe-body' >
    <iframe class='iframe fl' src="{{ item.url }}" marginwidth="0" marginheight="0" vspace="0" hspace="0" border="0" id='iframeid'></iframe>
  </div>


</body>
</html>

bookmark/templates/bookmark/list.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class='container'>
  <ul>
  {% for l in lists %}

    <li>
      <form action='{% url "list_update" l.id %}' method='post'>
        {% csrf_token %}
        <div class='edit-lists'>
          <input class='input' name='name' value='{{ l.name }}'>
          <input class='update' type='submit' value='更新'>
          <a href="{% url 'list_delete' l.id %}" title='删除分类，书签归入默认分类' class='del'>删除分类</a>
          <a href="{% url 'list_delete_all' l.id %}" title='删除分类及分类里所有的书签' class='delall ml15'>删除所有</a>
        </div>
      </form>
    </li>

  {% endfor %}
  </ul>
</div>

<script type="text/javascript">
$('.update').click(function() {
  if (!$(this).prev().val()) {
    alert('请输入分类名称');
    return false;
  }
});

$('.del').click(function() {
  if (!confirm("删除分类，分类中的书签归入默认分类"))
    return false;
});

$('.delall').click(function() {
  if (!confirm("删除分类及分类里所有的书签"))
    return false;
});
</script>

{% endblock %}

bookmark/templates/bookmark/new.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class='container'>

  <form class='new-bookmark-form clearfix' action="/new/" method="post">
    {% csrf_token %}

    <div class='span8 edit fl'>
      <div class='blank clearfix'>
        <label for="id-url">书签链接:</label>
        <input class="input" maxlength="255" disabled='disabled' type="text" value="{{ item.url }}">
      </div>

      <div class='blank clearfix'>
        <label for="id-title">标题:</label>
        {{ form.title }}
        {{ form.title.errors }}
      </div>

      <div class='blank clearfix'>
        <label for="id-private">是否私有:</label>
        <input id="id-private" name="private" class='private' type="checkbox" value="1">
      </div>

      <div class='blank clearfix'>
        <input name="item" type="hidden" value="{{ item.id }}">
        <input name="url" type="hidden" value="{{ item.url }}">
      </div>

      <div class='blank clearfix'>
        <input class='btn' type='submit' value='保存'>
      </div>
    </div>

    <div class='span4 fr'>
      请选择分类
      <ul class='list-list'>
        {% for list in lists %}
          <li>
            <input class="list-checkbox" {% if list.name == '默认分类' %}checked='checked'{% endif %} id='list-{{ list.id }}' type='radio' name='list' value='{{ list.id }}'>
            <label for='list-{{ list.id }}'>{{ list.name }}</label>
          </li>
        {% endfor %}
      </ul>
      <div class='new-list'>
        <input class='new-list-name'>
        <input type='button' class='p5 new-list-sub btn' style='font-size: 12px; line-height: 20px; padding: 5px;' value='新建分类'>
      </div>
    </div>
  </form>

</div>

<script type="text/javascript">
//新建分类
var is = true;
$('.new-list-sub').click(function(){
    var name = $('.new-list-name').val();
    if (!name) {alert('请输新分类名称')};

    if (is) {
      $.post('/list/new/', {'name': name}, function(data){
        is = false;
        if (data.error) {
          alert(data.status)
        } else {
          $('.list-list').append('<li><input class="list-checkbox" id="list-' + data.value + '" type="radio" name="list" value="' + data.value + '"><label for="list-' + data.value + '">' + data.name + '<label/></li>');
          $('#list-'+data.value).click();
        };
        $('.new-list-name').val('');
        is = true;
      }, 'json');
    }
});

$('.new-bookmark-form').submit(function(){
  url = $('#id_url').val();
  title = $('#id_title').val();
  //l = $(".list-checkbox:checked").length;]
  l = $(".list-checkbox:checked").val()
  if (!l) {
    alert('请选择分类');
    return false;
  }
  if (!url && !title && !l)
    return false;
});
</script>
{% endblock %}

bookmark/templates/bookmark/reply.html
{% extends 'layouts/base.html' %}

{% block content %}
{% load my_duoshuo %}

<div class='container'>
  <div class='title'>书签: <a target="_blank" href="{{ item.url }}">{% if item.title %}{{ item.title }}{% else %}{{ item.url }}{% endif %}</a></div>
  {% duoshuo_comments item.url item.title item.user.id %}
</div>

{% endblock %}