ishuqian/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # ishuqian:
    url(r'^$', 'ishuqian.views.default', name='default'),
    url(r'^about/$', 'ishuqian.views.feedback', name='about'),
    url(r'^callback/(?P<social>\w+)/$','ishuqian.views.callback', name='callback'),
    url(r'^signin/$', 'ishuqian.views.signin', name='signin'),
    url(r'^logout/$','ishuqian.views.logout', name='logout'),
    url(r'^home/$', 'ishuqian.views.home', name='home'),
    url(r'^home/public/$', 'ishuqian.views.home_public', name='home_public'),
    url(r'^home/private/$', 'ishuqian.views.home_private', name='home_private'),
    url(r'^home/list/(?P<id>\d+)/$', 'ishuqian.views.home', name='home_list'),

    # bookmark
    url(r'^addurl/$', 'bookmark.views.addurl', name='addurl'),
    url(r'^new/$', 'bookmark.views.new', name='new_bookmark'),
    url(r'^edit/(?P<id>\d+)/$', 'bookmark.views.edit', name='bookmark_edit'),
    url(r'^delete/(?P<id>\d+)/$', 'bookmark.views.delete', name='bookmark_delete'),
    url(r'^list/new/$', 'bookmark.views.new_list', name='new_list'),
    url(r'^list/$', 'bookmark.views.list_index', name='list'),
    url(r'^list/(?P<id>\d+)/update/$', 'bookmark.views.list_update', name='list_update'),
    url(r'^list/(?P<id>\d+)/delete/$', 'bookmark.views.list_delete', name='list_delete'),
    url(r'^list/(?P<id>\d+)/delall/$', 'bookmark.views.list_delall', name='list_delete_all'),
    url(r'^bookmarks/change/$', 'bookmark.views.bookmarks_change', name='bookmarks_change'),
    url(r'^bookmarks/delete/$', 'bookmark.views.bookmarks_delete', name='bookmarks_delete'),
    url(r'^bookmarks/import/$', 'bookmark.views.bookmarks_import', name='bookmarks_import'),
    url(r'^bookmarks/export/$', 'bookmark.views.bookmarks_export', name='bookmarks_export'),
    # url(r'^item/(?P<id>\d+)/$', 'bookmark.views.item', name='item'),
    url(r'^item/(?P<id>\d+)/reply/$', 'bookmark.views.item_reply', name='item_reply'),
    url(r'^bookmark/(?P<id>\d+)/reply/$', 'bookmark.views.bookmark_reply', name='bookmark_reply'),
    url(r'^bookmark/(?P<id>\d+)/go/$', 'bookmark.views.bookmark_go', name='bookmark_go'),
    url(r'^item/(?P<id>\d+)/go/$', 'bookmark.views.item_go', name='item_go'),

    # user
    url(r'^user/(?P<id>\d+)/$', 'ishuqian.views.user', name='user_index'),
    url(r'^user/feed/$', 'ishuqian.views.follow_bookmarks', name='user_follow_feed'),
    url(r'^user/(?P<id>\d+)/list/(?P<cate>\d+)/$', 'ishuqian.views.user', name='user_index_cate'),
    url(r'^user/follow/$', 'ishuqian.views.follow', name='user_follow'),
    url(r'^user/(?P<id>\d+)/following/$', 'ishuqian.views.following', name='user_following'),
    url(r'^user/(?P<id>\d+)/followers/$', 'ishuqian.views.followers', name='user_followers'),

    # favorite
    url(r'^favorite/(?P<id>\d+)/people/$', 'ishuqian.views.favorite_people', name='favorite_people'),


    # url(r'^ishuqian/', include('ishuqian.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ staticfiles_urlpatterns()

if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

bookmark/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class List(models.Model):

    user      = models.ForeignKey('ishuqian.User')
    name      = models.CharField(max_length=90)
    bookmarks = models.PositiveIntegerField(default=0)
    color     = models.CharField(max_length=10, blank=True)
    addtime   = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Item(models.Model):

    url             = models.URLField(max_length=255, blank=True)
    title           = models.CharField(max_length=255, blank=True)
    favorites       = models.PositiveIntegerField(default=0)
    point           = models.PositiveIntegerField(default=0)
    votes           = models.PositiveIntegerField(default=0)
    addtime         = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

class Bookmark(models.Model):

    user        = models.ForeignKey('ishuqian.User')
    list        = models.ForeignKey(List)
    item        = models.ForeignKey(Item, null=True, blank=True)
    url         = models.URLField(max_length=255, blank=True)
    title       = models.CharField(max_length=255)
    private     = models.PositiveSmallIntegerField(default=0)
    views_count = models.PositiveIntegerField(default=0)
    addtime     = models.DateTimeField(auto_now_add=True)
    updatetime  = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

ishuqian/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class User(models.Model):

    linked_account   = models.CharField(max_length=100, unique=True)
    linked_type      = models.CharField(max_length=10, blank=True)
    email            = models.EmailField(max_length=90, blank=True)
    username         = models.CharField(max_length=90, unique=True)
    password         = models.CharField(max_length=50)
    gender           = models.PositiveSmallIntegerField(default=0)
    avatar           = models.CharField(max_length=255)
    avatar_thumbnail = models.CharField(max_length=255, blank=True)
    location         = models.CharField(max_length=90)
    bookmarks_count  = models.PositiveIntegerField(default=0)
    following        = models.PositiveIntegerField(default=0)
    followers        = models.PositiveIntegerField(default=0)
    point            = models.PositiveSmallIntegerField(default=0)
    state            = models.PositiveSmallIntegerField(default=0)
    access_token     = models.CharField(max_length=255, blank=True)
    expires_in       = models.CharField(max_length=255, blank=True)
    created_at       = models.DateTimeField(auto_now_add=True)
    last_login       = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return self.username

    def update_bookmarks(self):
        self.bookmarks_count = self.bookmark_set.count()
        self.save()


class Follow(models.Model):

    fans       = models.ForeignKey(User, related_name='fans')
    hero       = models.ForeignKey(User, related_name='hero')
    created_at = models.DateTimeField(auto_now_add=True)

ishuqian/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils import simplejson
from django.db import connection

from utils.sina import get_user_info
from utils import login_required
from models import User, Follow
from bookmark.models import Bookmark, List, Item


def default(request):
    items = Item.objects.exclude(title='').order_by('-addtime')
    return render(request, 'welcome/default.html', {'items': items})


# 查看收藏书签的用户
def favorite_people(request, id):
    item = get_object_or_404(Item, id=id)
    people = item.bookmark_set.exclude(private=1)
    return render(request, 'favorite/people.html', {'people': people, 'item': item})


def callback(request, social):
    if social == 'weibo':
        u = get_user_info(request.GET['code'])
        u[0]['gender'] = 1 if u[0]['gender'] == 'm' else 0
        try:
            user = User.objects.get(linked_account=u[0]['id'])
            user.username         = u[0]['screen_name']
            user.location         = u[0]['location']
            user.avatar           = u[0]['avatar_large']
            user.avatar_thumbnail = u[0]['profile_image_url']
            user.gender           = u[0]['gender']
            user.access_token     = u[1].access_token
            user.expires_in       = u[1].expires_in
            user.save()

        except User.DoesNotExist:
            user = User(linked_account=u[0]['id'], username=u[0]['screen_name'],
                        location=u[0]['location'], gender=u[0]['gender'], linked_type='sina',
                        avatar=u[0]['avatar_large'], avatar_thumbnail=u[0]['profile_image_url'],
                        access_token=u[1].access_token, expires_in=u[1].expires_in)
            user.save()

            List.objects.create(name=u'默认分类', user=user)

        finally:
            request.session['id'] = user.id
            request.session['username'] = user.username
            request.session['avatar'] = user.avatar_thumbnail
    # elif social == 'qq':
    #     pass
    # else:
    #     pass
    if request.session.get('redirect_url', None):
        redirect_url = request.session.get('redirect_url', None)
        del request.session['redirect_url']
        return redirect('/addurl?url=' + redirect_url)
    return redirect('/')


def signin(request):
    if request.session.get('id', None):
        return redirect('default')
    return render(request, 'welcome/signin.html')


def logout(request):
    request.session.flush()
    return redirect('/')


@login_required
def home(request, id=0):
    user = User.objects.get(id=request.session.get('id', None))
    if id:
        list = get_object_or_404(List, id=id)
        bookmarks = list.bookmark_set.all().order_by('-updatetime')
    else:
        bookmarks = user.bookmark_set.all().order_by('-updatetime')
    return render(request, 'welcome/home.html', {'user': user, 'bookmarks': bookmarks, 'list_id': int(id)})

# return render(request, 'debug.html', {'debug': bookmarks})


@login_required
def home_public(request):
    user = User.objects.get(id=request.session.get('id', None))
    bookmarks = user.bookmark_set.filter(private=0).order_by('-updatetime')
    return render(request, 'welcome/home.html', {'user': user, 'bookmarks': bookmarks, 'list_id': 'public'})


@login_required
def home_private(request):
    user = User.objects.get(id=request.session.get('id', None))
    bookmarks = user.bookmark_set.filter(private=1).order_by('-updatetime')
    return render(request, 'welcome/home.html', {'user': user, 'bookmarks': bookmarks, 'list_id': 'private'})


# user
def user(request, id, cate=None):
    user = get_object_or_404(User, id=id)
    if cate is None:
        bookmarks = user.bookmark_set.order_by('-updatetime')
        list_id = 0
    else:
        cate = List.objects.get(id=cate, user=user)
        bookmarks = cate.bookmark_set.order_by('-updatetime')
        list_id = cate.id

    fans = request.session.get('id',None)
    if fans is None or fans == user.id:
        is_follow = 'none'
    else:
        try:
            f = Follow.objects.get(fans_id=fans, hero=user)
        except Follow.DoesNotExist:
            is_follow = 'no'
        else:
            is_follow = 'yes'
    # list_id = cate if cate is None else 0
    return render(request, 'user/show.html', {'user': user, 'bookmarks': bookmarks, 'list_id': list_id, 'follow': is_follow})


# 查看关注的人的书签
@login_required
def follow_bookmarks(request):
    user = get_object_or_404(User, id=request.session.get('id', None))
    follows = user.fans.all()
    bookmarks = Bookmark.objects.filter(user__in=[i.hero for i in follows]).exclude(private=1).order_by('-addtime')
    return render(request, 'user/follow_bookmarks.html', {'user': user, 'bookmarks': bookmarks, 'count': bookmarks.count()})


# 关注和取消关注
@csrf_exempt
@login_required
def follow(request):
    if request.method == 'POST':
        try:
            fans = User.objects.get(id=request.session.get('id', None))
            hero = User.objects.get(id=request.POST.get('id', None))
        except User.DoesNotExist:
            json = simplejson.dumps({'error': 1, 'message': u'r u kidding?'})
        else:
            try:
                relation = Follow.objects.get(fans=fans, hero=hero)
            except Follow.DoesNotExist:
                Follow.objects.create(fans=fans, hero=hero)
                status = 'followed'
            else:
                relation.delete()
                status = 'unfollowed'
            finally:
                fans.following = fans.fans.count()
                fans.save()
                hero.followers = hero.hero.count()
                hero.save()
                json = simplejson.dumps({'error': 0, 'message': status, 'followers': hero.followers})

        return HttpResponse(json)


def following(request, id):
    user = get_object_or_404(User, id=id)
    people =  user.fans.all()
    return render(request, 'user/follow_people.html', {'people': people, 'current': 'following', 'user': user}) 


def followers(request, id):
    user = get_object_or_404(User, id=id)
    people =  user.hero.all()
    return render(request, 'user/follow_people.html', {'people': people, 'current': 'followers', 'user':user })


def feedback(request):
    return render(request, 'welcome/feedback.html')

ishuqian/templates/user/follow_bookmarks.html
{% extends 'layouts/base.html' %}

{% block content %}

{% load pagination_tags %}
{% autopaginate bookmarks 25 %}

<div class='container clearfix'>
  <div class='span3 fl'>
    <div class='bookmarks-feed list-wrapper'>
      <h3 class='list-title clearfix'>书签流</h3>
      <ul class='home-list'>
        <li class='bt0'>
          朋友的书签
        </li>
<!--         <li>
          <a href="/home/">顶过的书签</a>
        </li> -->
      </ul>
    </div>

    <div class='bookmarks-feed list-wrapper mt20'>
      <h3 class='list-title clearfix'>工具</h3>
      <ul class='home-list'>
        <li class='bt0'>
          <a href="/bookmarks/import/">导入书签</a>
        </li>
        <li>
          <a href="/bookmarks/export/">导出书签</a>
        </li>
        <li>
          <div>
            <p>拖动下面的按钮到书签栏</p>
            <a class='bookmarklet' href="javascript:(function(){ var url = document.location; if(!url) throw(0); location.href='http://ishuqian.com/addurl?url=' + encodeURIComponent(url) }())">收藏到爱书签</a>
          </div>
        </li>
      </ul>
    </div>

    <div class='bookmark-list list-wrapper mt20'>
      <h3 class='list-title clearfix'>
        <div class='fl'>收藏夹</div>
        <a href="/list/" class="edit-list ml40 fl">分类管理</a>
        <a href="#" class="new-list mr20 fr">新建分类</a>
      </h3>
      <div class='new-list-input'>
        <input class='new-list-name'>
        <input type='button' class='p5 new-list-sub btn' value='确定'>
      </div>
      <ul class='home-list ajax-lists'>
        <li class='bt0'>
          <a href="{% url 'home_public' %}">公开书签</a>
        </li>

        <li>
          <a href="{% url 'home_private' %}">私有书签</a>
        </li>

        <li class='bt0'>
          <a href="/home/">所有书签</a>&nbsp;<span class='count'>({{ user.bookmarks_count }})</span>
        </li>
        
      {% for l in user.list_set.all %}
        <li>
          <a href="{% url 'home_list' l.id %}">{{ l.name }}</a>&nbsp;<span class='count'>({{ l.bookmarks }})</span>
        </li>
      {% endfor %}
      </ul>
    </div>

  </div>

 
  <div class='bookmark-list span9 fr'>
  {% for b in bookmarks %}
    <div class='home-item clearfix'>
      <div class='main fl'>
        <div class='feedtitle span8 oh' style='height:40px;'><a target='_blank' href="{{ b.url }}">{{ b.title }}</a></div>
        <div class='feeduser mb10'>
          <span><a href="{% url 'addurl' %}?url={{ b.url }}">收藏</a></span>
          <span><a href="{% url 'bookmark_reply' b.id %}">评论</a></span>
          <span class='ml15'><a href="{% url 'user_index' b.user.id %}">{{ b.user.username }}</a></span>
          <span class='addtime'>{{ b.addtime | date:"M d, Y" }}</span>
          <!-- JiaThis Button BEGIN -->
          <div class='fr' onmouseover="setShare('{{ b.title }} | #爱书签#', 'http://ishuqian.com/bookmark/{{b.id}}/go/);"> <!--自定义第一个分享标题和链接-->
             <div class="jiathis_style">      
             <a href="http://www.jiathis.com/share/?uid=1789726" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank">分享</a>
             </div>
          </div>
          <!-- JiaThis Button END -->
        </div>
      </div>
    </div>
  {% endfor %}
  {% paginate %}
  </div>

</div>

<script type="text/javascript">
var c = true;
$('.new-list').click(function(){
  $('.new-list-input').toggle(0, function(){
    if (c) {
      $('.new-list').html('取消');
      $('.new-list-name').focus();
      c = false;
    } else {
      $('.new-list-name').val('');
      $('.new-list').html('新建分类');
      c = true;
    };
  });
});

//新建分类
var is = true;
$('.new-list-sub').click(function(){
  var name = $('.new-list-name').val();
  if (!name) {alert('请输新分类名称')};
  if (is) {
    $.post('/list/new/', {'name': name}, function(data){
      is = false;
      if (data.error) {
        alert(data.status)
      } else {
        $('.ajax-lists').append('<li><a href="/home/list/' + data.value + '/">' + data.name + '</a>&nbsp;<span class="count">(0)</span></li>');
        var obj = document.getElementById("select-list");
        obj.add(new Option(data.name,data.value)); 
        //$('.select-list').append('<option value=' + data.value + '>' + data.name + '</option>');
        $('.new-list').click();
      };
      is = true;
    }, 'json');
  }
});
</script>
<!--单页面使用多分享按钮需要增加的分享参数代码-->                       
<script type="text/javascript">
function setShare(title, url) {
  jiathis_config.title = title;
  jiathis_config.url = url;
}
var jiathis_config = {
  appkey: {
    'tsina': 3120994132
  }
}
</script>  
<!--分享参数代码结束-->
<!--分享功能代码统一放到页尾-->
<script type="text/javascript" src="http://v1.jiathis.com/code/jia.js?uid=1789726" charset="utf-8"></script>
<!--分享功能代码结束-->
{% endblock %}

ishuqian/templates/user/follow_people.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class='container clearfix'>
  <div class='span3 fl'>
    <div class='bookmarks-feed list-wrapper p10'>
      <img width='200' height='200' src="{{ user.avatar }}">
      <div class='mt15 username'>{{ user.username }}</div>
      <div class='mt10 clearfix w121'>
        <span class='follow-num fl pr10'>
          {% if current == 'following' %}
            {{ user.following }}
          {% else %}
            <a href="{% url 'user_following' user.id %}">{{ user.following }}</a>
          {% endif %}
          <br>关注
        </span>
        <span class='follow-num fl pl10'>
          {% if current == 'followers' %}
            {{ user.followers }}
          {% else %}
            <a class='followers' href="{% url 'user_followers' user.id %}">{{ user.followers }}</a>
          {% endif %}
          <br>粉丝
        </span>
      </div>
      {% if follow == 'yes' %}
        <div><a class='mt10 following follow' href="javascript:">正在关注</a></div>
      {% elif follow == 'no' %}
        <div><a class='mt10 unfollow follow' href="javascript:">关注</a></div>
      {% endif %}
    </div>

    <div class='bookmark-list list-wrapper mt20'>
      <h3 class='list-title clearfix'>
        <div class='fl'>收藏夹</div>
      </h3>
      <ul class='home-list ajax-lists'>
        <li class='bt0'>
          {% if list_id == 0 %}
            所有书签&nbsp;<span class='count'><b>({{ user.bookmarks_count }})</b></span>
          {% else %}
            <a href="{% url 'user_index' user.id %}">所有书签</a>&nbsp;<span class='count'>({{ user.bookmarks_count }})</span>
          {% endif %}
        </li>
      {% for l in user.list_set.all %}
        <li>
          {% if list_id == l.id %}
            {{ l.name }}&nbsp;<span class='count'><b>({{ l.bookmarks }})</b></span>
          {% else %}
            <a href="{% url 'user_index_cate' user.id l.id  %}">{{ l.name }}</a>&nbsp;<span class='count'>({{ l.bookmarks }})</span>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    </div>

  </div>

  <div class='bookmark-list span9 fr'>
    <ul class='favorite-people clearfix'>
    {% for p in people %}
      {% if current == 'following' %}
        <a href="{% url 'user_index' p.hero.id %}">
          <li {% if forloop.counter == 1 %}class='ml0'{%else%}class='ml20'{% endif %}>
            <div class='favorite-person clearfix'>
              <img class='fl' width='30' height='30' src="{{ p.hero.avatar_thumbnail }}">
              <span>{{ p.hero.username }}</span>
            </div>
          </li>
        </a>
      {% elif current == 'followers' %}
        <a href="{% url 'user_index' p.fans.id %}">
          <li {% if forloop.counter == 1 %}class='ml0'{%else%}class='ml20'{% endif %}>
            <div class='favorite-person clearfix'>
              <img class='fl' width='30' height='30' src="{{ p.fans.avatar_thumbnail }}">
              <span>{{ p.fans.username }}</span>
            </div>
          </li>
        </a>
      {% endif %}
    {% endfor %}
    </ul>
  </div>
</div>

<script type="text/javascript">
  var id = '{{ user.id }}';
  var is = true;
  
  // 关注
  $('.follow').click(function(){
    if (is) {
      $.post('/user/follow/', {id: id}, function(data){
        is = false;
        if (data.error) {
          alert(data.message);
        } else {
          if (data.message == 'followed') {
            $('.follow').removeClass('unfollow');
            $('.follow').addClass('following');
            $('.follow').html('正在关注');
            $('.followers').html(data.followers);
          } else if(data.message == 'unfollowed') {
            $('.follow').removeClass('following');
            $('.follow').addClass('unfollow');
            $('.follow').html('关注');
            $('.followers').html(data.followers);
          }
        }
        is = true;
      }, 'json');
    };
  });

</script>

{% endblock %}

ishuqian/templates/user/show.html
{% extends 'layouts/base.html' %}

{% block content %}

{% load pagination_tags %}
{% autopaginate bookmarks 25 %}

<div class='container clearfix'>
  <div class='span3 fl'>
    <div class='bookmarks-feed list-wrapper p10'>
      <img width='200' height='200' src="{{ user.avatar }}">
      <div class='mt15 username'>{{ user.username }}</div>
      <div class='mt10 clearfix w121'>
        <span class='follow-num fl pr10'><a href="{% url 'user_following' user.id %}">{{ user.following }}</a><br>关注</span>
        <span class='follow-num fl pl10'><a class='followers' href="{% url 'user_followers' user.id %}">{{ user.followers }}</a><br>粉丝</span>
      </div>
      {% if follow == 'yes' %}
        <div><a class='mt10 following follow' href="javascript:">正在关注</a></div>
      {% elif follow == 'no' %}
        <div><a class='mt10 unfollow follow' href="javascript:">关注</a></div>
      {% endif %}
    </div>

    <div class='bookmark-list list-wrapper mt20'>
      <h3 class='list-title clearfix'>
        <div class='fl'>收藏夹</div>
      </h3>
      <ul class='home-list ajax-lists'>
        <li class='bt0'>
          {% if list_id == 0 %}
            所有书签&nbsp;<span class='count'><b>({{ user.bookmarks_count }})</b></span>
          {% else %}
            <a href="{% url 'user_index' user.id %}">所有书签</a>&nbsp;<span class='count'>({{ user.bookmarks_count }})</span>
          {% endif %}
        </li>
      {% for l in user.list_set.all %}
        <li>
          {% if list_id == l.id %}
            {{ l.name }}&nbsp;<span class='count'><b>({{ l.bookmarks }})</b></span>
          {% else %}
            <a href="{% url 'user_index_cate' user.id l.id  %}">{{ l.name }}</a>&nbsp;<span class='count'>({{ l.bookmarks }})</span>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    </div>

  </div>

  <div class='bookmark-list span9 fr'>
  {% for b in bookmarks %}
    <div class='home-item clearfix'>
      <div class='main fl'>
        <div class='feedtitle span8 oh' style='height:40px;'><a target='_blank' href="{{ b.url }}">{{ b.title }}</a></div>
      </div>
    </div>
  {% endfor %}
  {% paginate %}
  </div>
</div>

<script type="text/javascript">
  var id = '{{ user.id }}';
  var is = true;
  
  // 关注
  $('.follow').click(function(){
    if (is) {
      $.post('/user/follow/', {id: id}, function(data){
        is = false;
        if (data.error) {
          alert(data.message);
        } else {
          if (data.message == 'followed') {
            $('.follow').removeClass('unfollow');
            $('.follow').addClass('following');
            $('.follow').html('正在关注');
            $('.followers').html(data.followers);
          } else if(data.message == 'unfollowed') {
            $('.follow').removeClass('following');
            $('.follow').addClass('unfollow');
            $('.follow').html('关注');
            $('.followers').html(data.followers);
          }
        }
        is = true;
      }, 'json');
    };
  });

</script>

{% endblock %}